language: python
python:
 - 3.5
 - 3.6
 - 3.7
install:
  - pip install tox
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export TOXENV=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export TOXENV=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export TOXENV=py37; fi"
script:
  - tox
