include: https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml

variables:
  RELEASE: 'unstable'
  DEBFULLNAME: "Liip Gitlab CI"
  DEBEMAIL: "<sysadmin+taxi@liip.ch>"

stages:
    - build
    - deploy

build:
  extends: .build-package
  tags:
      - docker

deploy:
    stage: deploy
    before_script:
        - echo "* Attempt SSH to the destination host"
        - tmpkey=$(mktemp)
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" > $tmpkey
        - ssh-add $tmpkey
        - rm -f $tmpkey
        - ssh -o StrictHostKeyChecking=no -p 2201 liip@taxi-packages.liip.ch echo 'OK'
    script:
      - echo "* Upload the unsigned packages"
      - for c in ${WORKING_DIR}/*.changes; do echo "  - $c"; for f in $(grep -A1000 'Files:' $c | tail -n+2 | cut -f6 -d' '); do echo "    -> $f"; scp -o StrictHostKeyChecking=no -P 2201 ${WORKING_DIR}/$f liip@taxi-packages.liip.ch:~/taxi-packages-incoming/ ; done; echo "    -> $c"; scp -o StrictHostKeyChecking=no -P 2201 $c liip@taxi-packages.liip.ch:~/taxi-packages-incoming/ ; done
